name: Run tests

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run unittest
        run: |
          python -m unittest test_main_unit.py

  pytest:
    needs: unittest  # Зависит от успешного завершения unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest
        run: pytest test_main_pytest.py -v
